{"version":3,"sources":["interceptor/exception.interceptor.ts"],"names":[],"mappings":";;;;;;;;AAAA,2CAA8F;AAE9F,mCAAiC;AAGjC,IAAa,oBAAoB,GAAjC;IAEI,SAAS,CAAC,OAAyB,EAAE,OAAwB;QAEzD,OAAO,OAAO,CAAC,KAAK,CAAC,CAAC,GAAG,EAAE,MAAM,EAAO,EAAE;YACtC,IAAI,GAAG,YAAY,sBAAa,EAAE;gBAC9B,OAAO,OAAO,CAAC,OAAO,CAAC;oBACnB,IAAI,EAAE,GAAG,CAAC,SAAS,EAAE;oBACrB,OAAO,EAAE,GAAG,CAAC,WAAW,EAAE;iBAC7B,CAAC,CAAC;aACN;iBAAM;gBACH,OAAO,OAAO,CAAC,OAAO,CAAC;oBACnB,IAAI,EAAE,GAAG;oBACT,OAAO,EAAE,SAAS,GAAG,GAAG,CAAC,QAAQ,EAAE;iBACtC,CAAC,CAAC;aACN;QACL,CAAC,CAAC,CAAC;IACP,CAAC;CACJ,CAAA;AAlBY,oBAAoB;IADhC,mBAAU,EAAE;GACA,oBAAoB,CAkBhC;AAlBY,oDAAoB","file":"exception.interceptor.js","sourcesContent":["import { ExecutionContext, HttpException, Injectable, NestInterceptor } from \"@nestjs/common\";\nimport { Observable } from \"rxjs\";\nimport \"rxjs/add/operator/catch\";\n\n@Injectable()\nexport class ExceptionInterceptor implements NestInterceptor {\n\n    intercept(context: ExecutionContext, stream$: Observable<any>): Observable<any> {\n\n        return stream$.catch((err, caught): any => {\n            if (err instanceof HttpException) {\n                return Promise.resolve({\n                    code: err.getStatus(),\n                    message: err.getResponse()\n                });\n            } else {\n                return Promise.resolve({\n                    code: 500,\n                    message: \"出现了意外错误\" + err.toString()\n                });\n            }\n        });\n    }\n}\n"]}